name: "Assign reviewers"
on:
  pull_request:
    # types:  [ ready_for_review ]
    branches: [ master ]

jobs:
  assign_reviewer:
    name: Assign reviews
    runs-on: ubuntu-latest
    steps:
      - name: Get CIRCT
        uses: actions/checkout@v2
      - name: apply-herald-rules
        id: herald
        uses: gagoar/use-herald-action@v2.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          rulesLocation: 'codeowners/'
          DEBUG: '*'

      - name: Store response payload to file
        run: echo '${{ steps.herald.outputs.appliedRules }}'
