name: Check code format

on: [push, pull_request]

jobs:
  build:
    name: Check with clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Get CIRCT
      uses: actions/checkout@v2
      with:
        submodules: 'false'
        ref: ${{ github.head_ref }}
        fetch-depth: 5
    - name: clang-format
      run: |
        CHANGED_FILES=`git diff --name-only -r HEAD~ | grep -E '.(c|cpp|h|hpp)$' | xargs`
        [ -z "$CHANGED_FILES" ] && exit 0
        clang-format -i $CHANGED_FILES
        git diff > clang-format.patch
        [ -s clang-format.patch ] && exit 0
        echo "Clang-format found formatting problems. See diff in the clang-format.patch artifact."
        exit 1
    - name: Upload clang-format patch
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        # name: clang-format.patch
        path: clang-format.patch
