name: Check code format

on: [push, pull_request]

jobs:
  build:
    name: Check with clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Get CIRCT
      uses: actions/checkout@v2
      with:
        submodules: 'false'
    - name: clang-format
      run: |
        CHANGED_FILES=`git diff --name-only HEAD~1 | grep -E '.(c|cpp|h|hpp)$' | xargs`
        clang-format -i $CHANGED_FILES
        git diff > clang-format.patch
        if [ -s clang-format.patch ]; then
          exit 0
        fi
        echo "Clang-format found formatting problems. See diff in the clang-format.patch artifact."
        exit 1
    - name: Upload clang-format patch
      uses: actions/upload-artifact@v2
      with:
        # name: clang-format.patch
        path: clang-format.patch
